Update README.md
top-gg/crowdin-discord pull request #11
Opened 2022-07-30 23:39 UTC by IThundxr

2022-07-30 23:43 UTC, Hopefuls requested changes

2022-07-30 23:43 UTC, Hopefuls commented on README.md
> +# open index.ts , go to line №7 and replace 'webook' with Discord Webhook URL
Misspelled

2022-07-30 23:45 UTC, IThundxr commented
Fixed small issues :D

2022-07-31 21:48 UTC, Hopefuls approved these changes

2022-09-03 15:27 UTC, merged